### PR TITLE
Readme fix

### LINKED ISSUE #40: Typo in README.md
There is a spelling mistake for the word `fork` under the `Contribution Guidelines` in the readme.md file.

e0

### PR DESCRIPTION
**Pull request by vrouilhac**
I fixed the typo in Readme file ( "form" -> "fork" ). And I also added contributors profile image clickable instead of just the name as I saw it suggested. Please let me know what you think of that version.

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@Vincent-Projects you fixed typo mistake in readme.md file, but I don't want to show contributors images with their name manually It should be automatically update when new contributors contribute in any issue.

Only correct typo mistake and update PR if you can not arrange contributors images dynamically. 

Which open source program you part of GSSOC or CrossWoc?

**Comment by vrouilhac** [comment]
I removed the image. Only keeping the typo fix.
But I don't understand what GSSOC or CrossWoc means?

**Comment by pankajkumarbij** [comment]
> But I don't understand what GSSOC or CrossWoc means?

I means are you part of any open source program or independent contribution?

**Review by pankajkumarbij — APPROVED** [review]

**Comment by vrouilhac** [comment]
> > But I don't understand what GSSOC or CrossWoc means?
> 
> I means are you part of any open source program or independent contribution?

I'm not part of any program, I did not know they exist. I just wanted to see if I can help here and there to make my first contributions.

**Comment by pankajkumarbij** [comment]
> > > But I don't understand what GSSOC or CrossWoc means?
> > 
> > 
> > I means are you part of any open source program or independent contribution?
> 
> I'm not part of any program, I did not know they exist. I just wanted to see if I can help here and there to make my first contributions.

Great

**Pull request merged**
