### PR TITLE
interactive login signup

### LINKED ISSUE #35: Improve Login Page and Sign Up page design for Students
Improve Login Page and Sign Up page design for students

- You can use input fields name, email, mobile no, password, confirm the password, agree on the checkbox, and can suggest other features also for the sign-up page.
- Login page only has email and password input fields and agrees on the checkbox.
- All pages should be in dark mode with the best color combination because this website is building up in dark mode.
- Make sure use only react-bootstrap and CSS for style, don't use any other styling framework or libraries.
- Make sure every page should be responsive on every platform.

### PR DESCRIPTION
**Pull request by raman-thakur**
@pankajkumarbij  As per the requirements i have redesigned the appearance of login and signup pages and now pages are looking cool.
also, the site is still responsive.

### CODE REVIEW

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
Login and Sign-up forms not responsive at all.
Please Explore some bootstrap login and sign-up templates and make them responsive.

Screenshot of React App

**Comment by pankajkumarbij** [comment]
Look at some dark mode login and signup templates in bootstrap and make it accordingly and a background that is like yellow is not suit, make it in a simple bootstrap card with dark, blue, or maybe a white background.

Example of a form card:- 

Screenshot of Covid-19 Tracker

**Comment by raman-thakur** [comment]
i was talking about the image in the background is responsive @pankajkumarbij

**Comment by pankajkumarbij** [comment]
> i was talking about the image in the background is responsive @pankajkumarbij

@raman-thakur yeah image is nicely responsive and image format is a good combination with this website but the design of the form is the most important part of this issue.

**Comment by raman-thakur** [comment]
@pankajkumarbij now forms and each and every element of forms are responsive pls review once!

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@raman-thakur  Form Design is not up to the mark this type of form design is already exists in the project.

Check some references: (you can check code and everything of that template but don't copy directly.)

1.  https://jsfiddle.net/StartBootstrap/amxr8n19/
2.  https://codepen.io/emreberber/pen/oeREoZ
3.  https://epicbootstrap.com/snippets/registration
4.  https://epicbootstrap.com/snippets/login-form-dark

My preference is 2nd or 3rd anyone form design.
You have to change only the form design, not the background image and all.

**Comment by raman-thakur** [comment]
@pankajkumarbij is this good now??

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@raman-thakur Nice Work, One more change is required then I will merge the PR.

Set or change in .container class in register.css ```width: 60%; opacity:75% ;border-radius: 1%;``` and in button class there is not need ```border-radious``` so remove it.

**Comment by raman-thakur** [comment]
> @raman-thakur Nice Work, One more change is required then I will merge the PR.
> 
> Set or change in .container class in register.css `width: 60%; opacity:75% ;border-radius: 1%;` and in button class there is not need `border-radious` so remove it.

@pankajkumarbij done sir, this was amazing to work upon this project and your guidance was just osm!

**Comment by pankajkumarbij** [comment]
@raman-thakur Amazing Work and nicely follow all guidelines that I required changes.

Open Source Programs are for a great learning experience. Don't frustrated and work according to your mentor you will learn a lot.

I am like your brother please don't use ```sir``` keyword.

Thanks for contributing to this project.

**Pull request merged**
