### PR TITLE
Search filter applied for jobs and internships

### LINKED ISSUE #201: Filters while looking for jobs and internships (backend)
## Using filters while looking for jobs and internships
A student is currently not allowed to search for jobs/internships with filters

The backend logic I'll add will enable a student to look for jobs/internships using filters:
1. location
2. duration
3. tech stack
4. company name
5. start date

@pankajkumarbij I will work on the backend part of this, could you please assign this issue to me?

### PR DESCRIPTION
**Pull request by mitalirs**
Added the search filter for Jobs and Internships, a student can use filters as per his/her requirement
After adding an appropriate query string, the search filter works fine. I tested the routes.
For filtering according to technical requirements:
1. only one skill -  /searchFilterJobs?techstack=skill1
2. more than 1 skill - /searchFilterJobs?techstack=skill1&techstack=skill2

Note: If 2 skills are added, the internship(s)/job(s) having either/both of them as requirement(s) will be listed (similar process will be there for more than 2 skills)

### CODE REVIEW

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@mitalirs You have not added this feature for fresher's job.

**Comment by mitalirs** [comment]
@pankajkumarbij I have added the filter for fresher jobs now, can you please review it

**Comment by pankajkumarbij** [comment]
@mitalirs please resolve the conflict.

**Review by pankajkumarbij — APPROVED** [review]

**Comment by mitalirs** [comment]
@pankajkumarbij, done, resolved the conflict

**Pull request merged**
