### PR TITLE
Signout

### LINKED ISSUE #79: Creating signout route and write it's logic and Connect with react
## Describe the bug
After Logging in we can't make a logout request we have to manually clear data

## Solution
Create a signout Route at the backend and integrate it with React Front-End and Create a bottom in NavBar using Conditional rendering

### PR DESCRIPTION
**Pull request by hrushikesh-git**
Used the Conditional Rendering in React and based on the user is logged in or not the navbar functionality is toggled. Created a function **_isAuth()_** to check if there is any user logged in. If not the navbar will render the option of signing and login.
before-login

If the user is logged in the navbar will render the signout Button which beholds the signout functional and a custom welcome-{name} displaying users name
after-login

**### **Note:-**** The changes are marked in the red box, not part of the site

### CODE REVIEW

**Comment by hrushikesh-git** [comment]
@pankajkumarbij please guide me how should I resolve this conflicts

**Comment by pankajkumarbij** [comment]
@hrushikesh-git For solving the conflicts you should pull the changes that done after you forked the repo and other PR merged but for now I have solved conflicts for you.

**Comment by hrushikesh-git** [comment]
@pankajkumarbij thanks for helping man done conflicts are resolved please merge the PR

**Comment by hrushikesh-git** [comment]
> @hrushikesh-git For solving the conflicts you should pull the changes that done after you forked the repo and other PR merged but for now I have solved conflicts for you.

Thank you so much

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Nice Work
Thanks for contributing to this project.

**Pull request merged**
