### PR TITLE
Added Login and Signup modals and routes and Integrated with react 

### LINKED ISSUE #56: Integrate database with login and signup pages for students.
Integrate database with login and signup pages for students.

Use fetch in react for post and get data.

All mongoose-related schemas should be in the models folder in the server and route in the routes folder.

code formatting should be nice.

### LINKED ISSUE #68: MongoDb connection
Create mongodb connection in main server file.

Currently, mongodb connection is handled in routes files.

Move connection logic to server/index.js before app.listen statement.

Please follow error handling while connecting db.

### PR DESCRIPTION
**Pull request by hrushikesh-git**
add the schema for student modal and created routes for student signup and sign in, integrated it with react as well also made a change in the previous contact message and made the connectivity to database easy

signup success
signin success

### CODE REVIEW

**Comment by hrushikesh-git** [comment]
Also, improve the database connectivity #68 made it centralized and used in the index.js folder

**Comment by pankajkumarbij** [comment]
@asi309 please review this PR.

**Comment by pankajkumarbij** [comment]
@hrushikesh-git
please make a new branch for every new PR, don't make PR directly with the master branch next time.

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Very Nice Wok.
Thanks for contributing to this project.

**Comment by hrushikesh-git** [comment]
> @hrushikesh-git
> please make a new branch for every new PR, don't make PR directly with the master branch next time.

yes I will do that for sure thank you

**Pull request merged**
