### PR TITLE
Added the complete form Validations for both Employer SignIn and SignIn

### LINKED ISSUE #128: Validation Improvement in Signup Form
## Is your feature request related to a problem? Please describe.
I currently forked this repo and tried to signup in the signup form seciton with some random wrong details [ name , password , contact  etc . ]  and as a result it got submitted which is wrong for the project 

here's the demo 
githubissue

## Describe the solution you'd like
Being a GSSOC'21 Participant , I am interested to work and improve this project by adding some great validations . @pankajkumarbij  Can you please assign this to me with   " GSSOC "   and associated " Level "  Label  , so that I can start working on it to give best outcome

## Additional context
Add any other context about the feature request here.
No

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
Successfully added the complete form validations for both Employer SignUp and SignIn with successfull result

### CODE REVIEW

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@Jassi10000 Please send some screenshots related to it.

**Comment by Jassi10000-zz** [comment]
> @Jassi10000 Please send some screenshots related to it.

Sure , will share in next few minutes

**Comment by Jassi10000-zz** [comment]
@pankajkumarbij 

Sorry brother , I got busy 
Here are the screenshots

easyJobInternProof-1
easyJobInternProof-2


I have filled all the fields in the form incorrectly to show validations I have added

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@Jassi10000 Thanks for contributing to his project.

**Comment by Jassi10000-zz** [comment]
It my pleasure @pankajkumarbij , looking forward to contribute more

**Pull request merged**
