### PR TITLE
Added Login and Signin Gateway

### LINKED ISSUE #50: Integrate Login and Signup page for students with database.
Integrate Login and Signup page for students with database

Use mongoose(MongoDB) with Node.js(express.js) for store user details. (use local system MongoDB for store means don't use any online platform).

### PR DESCRIPTION
**Pull request by sparshsharma2510**
Fixes Issue #50

### CODE REVIEW

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@sparshsharma2510 Nice Work please resolve the conflicts.

**Comment by pankajkumarbij** [comment]
@sparshsharma2510

Contact us page backend merged so there is a conflict.
Take care of the contact us page also that information is stored or not after you update some files.

**Comment by sparshsharma2510** [comment]
I have tried to resolve the conflicts, Kindly check.

**Comment by pankajkumarbij** [comment]
@sparshsharma2510 Nice Work,
Thanks for contributing to this project.

**Pull request merged**
