### PR TITLE
Modified footer 

### LINKED ISSUE #287: Frontend: Footer
## Is your feature request related to a problem? Please describe.
I want to work in footer part. 
## Describe the solution you'd like
I want to change the footer's frontend part. I will create cutomize footer
## Additional context
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by Vishruta-Patil**
## Related issue?
close: #287

## Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I have added news-letter form. It is the responsive form.

## Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

## Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

## Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

## Open Source Program names (OPTIONAL)
If you participated in any open-source program then please mention the program name here

# Screenshots (Or Videos)

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **
Screenshot (1572)
Footer in desktop view

Screenshot (1573)

### CODE REVIEW

**Comment by Vishruta-Patil** [comment]
please review the PR

**Comment by Vishruta-Patil** [comment]
@pankajkumarbij Can you pls review the PR

**Comment by pankajkumarbij** [comment]
@Vishruta-Patil please share screenshots

**Comment by Vishruta-Patil** [comment]
I have added the screenshot @pankajkumarbij

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@Vishruta-Patil Nice Work
Thanks for contributing to this project.

**Comment by Vishruta-Patil** [comment]
@pankajkumarbij Thank you. Glad you liked it

> @Vishruta-Patil Nice Work
> Thanks for contributing to this project.



> @Vishruta-Patil Nice Work
> Thanks for contributing to this project.

Glad you liked it. Can you suggest me more to contribute in frontend or backend part

**Comment by Vishruta-Patil** [comment]
> @Vishruta-Patil Nice Work
> Thanks for contributing to this project.

Glad you liked it. Can you suggest me more to contribute in frontend or backend part

**Comment by pankajkumarbij** [comment]
> > @Vishruta-Patil Nice Work
> > Thanks for contributing to this project.
> 
> Glad you liked it. Can you suggest me more to contribute in frontend or backend part

@Vishruta-Patil yeah I will suggest you there are many works are done in backend but not in frontend

**Comment by pankajkumarbij** [comment]
@Vishruta-Patil DM me on discord I will suggest some issues you can solve because this is a closed PR here I am not able to find the msg.

**Pull request merged**
