### PR TITLE
made Contact us page responsive and improved design

### PR DESCRIPTION
**Pull request by sukhpreet-singh1**
improved contact us page and improved the design according to dark mode.

### CODE REVIEW

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@sukhpreet-singh1 contact form overlapping with footer in mobile view as well as in pc view also.

But I don't want to just simply a form it should be the standard look.

Check some examples on the internet to contact us page and improve it.

reference:-
https://bootsnipp.com/snippets/35VBm

**Comment by sukhpreet-singh1** [comment]
ok  i will make it look better

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 are you working on it?

**Comment by sukhpreet-singh1** [comment]
Yes I am working, I was little busy so tomorrow I will complete this issue

**Comment by pankajkumarbij** [comment]
> Yes I am working, I was little busy so tomorrow I will complete this issue

No problem I want to just confirm that you are working or not.

**Pull request closed without merging**
