### PR TITLE
Made the signup and login form for students mobile responsive and added the form validations for both.

### LINKED ISSUE #125: Making the login and signup form UI mobile responsive
## Is your feature request related to a problem? Please describe.
Right now the signup and login form are not mobile responsive.It is looking something like this in mobile view.

image

## Describe the solution you'd like
Instead it should be take the full width in mobile view like this.(Just an example)

image

Please assign this issue to me and let me fix this.

### PR DESCRIPTION
**Pull request by kartikpuri99**
Issue Number
ISSUE #125 

Describe the changes you've made
I have made the signup and login form mobile reponsive and have also added the signup,login validation logic for students and have made both the login and register component from class based to function based components.

image
image
image

Please review my PR and suggest any changes you want me to do.

### CODE REVIEW

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@kartikpuri99 Very Nice Work
Please add the same things for the employer sign-in and sign-up page also.
Employer login and register forms also should be responsive and validated.

If You want to work with the same issue then I will give Lebel3 for this issue or you can open another issue for this?

After you forked this repo some PR merged then please pull changes and check that signup and login for both companies and students are working fine or not before making a PR.

**Comment by kartikpuri99** [comment]
okay i will do it in the same issue only so don't merge the PR i will make a single PR only after adding validation for employer login and signup

**Comment by kartikpuri99** [comment]
okay i will do it in the same issue only so don't merge the PR i will make a single PR only after adding validation for employer login and signup

**Comment by kartikpuri99** [comment]
i already had pull the changes while working on the issue so you can merge this pr.

**Comment by kartikpuri99** [comment]
can i create two PR's in the same issue? If yes then i will add the employer sign in and login form validation in my next PR if it is okay with you in the same issue only.

**Comment by pankajkumarbij** [comment]
> can i create two PR's in the same issue? If yes then i will add the employer sign in and login form validation in my next PR if it is okay with you in the same issue only.

@kartikpuri99 I am merging it and you make another issue for employer signup and signing page responsive in mobile view so I can attach that issue with your next PR so your marks will be added in GSSOC leaderboard.

**Pull request merged**
