### PR TITLE
Fix #14 : added About Us page

### LINKED ISSUE #14: Design an about us page.
Design an about us page with react-bootstrap.

### PR DESCRIPTION
**Pull request by soumya-badkul**
Fix #14: Added responsive about us page
https://drive.google.com/file/d/12GuBRP22uxrUxsLgV2YrrXNk6FAPbJpx/view?usp=sharing

### CODE REVIEW

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@soumya-badkul About us page design is nice but make it a little bit small.
It too large.

**Comment by soumya-badkul** [comment]
okay

**Comment by soumya-badkul** [comment]
@pankajkumarbij 
image

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@soumya-badkul Nice Work.
Thanks for contributing to this project.

**Comment by soumya-badkul** [comment]
> @soumya-badkul Nice Work.
> Thanks for contributing to this project.

Pleasure

**Pull request merged**
