### PR TITLE
Added form validation to login and signup form

### LINKED ISSUE #97: login  and sign-up form validation for students.
Login and Sign-up form validation for students.

Use a proper validation method if the user does not enter valid field data then it should give an error msg in a proper format.

### PR DESCRIPTION
**Pull request by kartikpuri99**
Fixes #97

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Please Don't remove the PR template when you make a new PR.
Send Some screenshots that your work.

**Comment by kartikpuri99** [comment]
image
image
image

Is it good enough?

**Comment by pankajkumarbij** [comment]
The name does not need to be greater than 5 always.
The name should have only required.

**Comment by kartikpuri99** [comment]
okay i will change that it there anything else you want me to change?

**Comment by pankajkumarbij** [comment]
> okay i will change that it there anything else you want me to change?

Other things are perfect I think but the red color is not visible clearly.

**Comment by kartikpuri99** [comment]
yes i know i can bold the font if you want.

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
> yes i know i can bold the font if you want.

@kartikpuri99 It is a file for now.
Thanks for contributing to this project.

**Pull request merged**
