### PR TITLE
Added the email.js file for sending mail whenever a new user signs up

### LINKED ISSUE #86: Sending mail using nodemailer when a new user signs up.
I would like to add the functionality of sending a mail whenever a new user signs up to the app.
I am a participant of GSSOC'21.

If you find it relevant, please assign me to it and add the necessary tags.

### PR DESCRIPTION
**Pull request by udaymittal7**
I have created a new utils folder which contains the email.js file. We can use this email function for creating other necessary emails too.

I have included the file in user.js of routed folder and added the function in the signup route.

We have to add EMAIL_USERNAME and EMAIL_PASSWORD in the .env file for the nodemailer function to accept and send the email.

Please check and review it. If any improvement required, let me know.
Thank you.

### CODE REVIEW

**Comment by udaymittal7** [comment]
Please add the necessary tags here as I made this PR for #86 by mistake @pankajkumarbij.
Thank you.

**Comment by pankajkumarbij** [comment]
@udaymittal7 please resolve the conflicts by pulling changes from the original repo master branch.

**Comment by udaymittal7** [comment]
How to do that @pankajkumarbij ?

**Comment by pankajkumarbij** [comment]
> How to do that @pankajkumarbij ?

Pull the changes from the original repository master branch then conflicts will solve automatically.

If you don't know how to pull changes then first search commands for it.

**Comment by udaymittal7** [comment]
Done @pankajkumarbij

**Comment by pankajkumarbij** [comment]
@udaymittal7 Nice Work 
Thanks for contributing  to this project.

**Comment by udaymittal7** [comment]
@pankajkumarbij Thank you. I have created another issue. Please take a look. Thank you.

**Pull request merged**
