### PR TITLE
Student Profile Builder (issue #98)

### LINKED ISSUE #98: Student profile builder form
Student profile builder form where user can make own profile after login.

You need to make a front-end form only for all the given sections.

- Student Address
- Github Link
- Linkedin Link
- Other Profile Link (Codechef, Portfolio, any hackathon/coding website, etc) 
- Education (College/School name, Stream/Branch, Start Date, End Date, Performance Scale(Optional): CGPA/Percentage, etc, Performance(Optional), Status: pursuing/completed).
- Experience (Company/Organization name, Title, Start Date, End Date, Employment type, Location, Description (Optional))
- Projects (Project Name, Project Link(optional), Start Date, End Date, Description (Optional))
- Skills (Skills like Java, C++, etc.)
- Training/Courses (Coaching/Organization name, Title, Start Date, End Date, Location, Description (Optional))
- Achievements
- Other

All the above fields except Student Address, Github Link, Linkedin Link all other fields must be dynamic means a student can add any number of educations, skills, etc.

Design best-standered form using react-bootstrap.
You need to design the front-end part only.
After login a student there should be a button in the navbar to build own profile.

### PR DESCRIPTION
**Pull request by srk224**
Dynamic Student Profile Builder page created!

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@srk224, please use only js files instead of JSX files.

**Comment by srk224** [comment]
I have converted the files and committed the changes
@pankajkumarbij 
can you please take a look?

**Comment by pankajkumarbij** [comment]
@srk224 ok please resolve the conflicts.

**Comment by srk224** [comment]
@pankajkumarbij  I have resolved all the conflicts

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@srk224 Nice Work
Thanks for contributing to this project.

**Pull request merged**
