### PR TITLE
Modified mentor banner, added gif

### LINKED ISSUE #80: Enhancing the UI(readme.md)
Basically , we need to add an attractive poster so that people get to see our project.  A banner for mentors involved. We can also add a gif explaining how our objective works, this will convey the message very easily and attract the crowd.

### PR DESCRIPTION
**Pull request by aditisneh**

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@aditisneh Nice Work
One More change required Please remove the mentors' poster and use simple images with a username like admin.

**Comment by aditisneh** [comment]
@pankajkumarbij okay then

**Comment by aditisneh** [comment]
@ I was thinking not to add pictures, since we are removing the poster, it would be better to add other mentors aside yours in the table form.

**Comment by pankajkumarbij** [comment]
> @ I was thinking not to add pictures, since we are removing the poster, it would be better to add other mentors aside yours in the table form.

ok you can do that.

**Comment by aditisneh** [comment]
Done.

**Comment by pankajkumarbij** [comment]
@aditisneh Nice Work.
Thanks for contributing to this project.

Please don't make PR directly from the master branch, for every new PR you have to make a new branch.

**Comment by aditisneh** [comment]
@pankajkumarbij thanks. Ya sorry , i will consider that next time

**Pull request merged**
