### PR TITLE
removed warnings

### PR DESCRIPTION
**Pull request by Subham142**
#167

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@Subham142 please resolve the conflicts.

**Comment by Subham142** [comment]
@pankajkumarbij  can i make another PR  that will be more efficient way to handle this as I forgot to merge upstream in the beginning so therefore there's a conflict in the package.json

**Comment by Subham142** [comment]
I'll close this PR and make another in 30 mins or so

**Comment by pankajkumarbij** [comment]
@Subham142 I am closing this PR and make a fresh PR but you can make the PR later after some ongoing work will be done.

If you make PR now then there may be another conflict after merging another PR.

**Pull request closed without merging**
