### PR TITLE
Alert/Notify Feature has been added

### LINKED ISSUE #72: We can insert Alert messages
For the instruction of client, For ex:- After Login or signup a popup will came show that signup is successfull or if any error
alert

### PR DESCRIPTION
**Pull request by hrushikesh-git**
### Alert/Notify Added
As the user will sign-in or sign-up the user will get an idea if they have been successfully authorized, if not they will be alerted with further instructions. These messages won't stay there forever as soon as the user travel to a different page or try to enter information in login or signup for the message will disappear. State hooks of **react** have been used to display these.

alert error
 messages

alert login success

signup alert success

signup alert error

### CODE REVIEW

**Comment by hrushikesh-git** [comment]
Please review the Code and I am open to suggestions

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Nice Work
But there are no file changes is shown in PR, I think all files that you have changed are not pushed.

**Comment by hrushikesh-git** [comment]
> @hrushikesh-git Nice Work
> But there are no file changes is shown in PR, I think all files that you have changed are not pushed.

Please guide me what should i do as i am new to git hub

**Comment by hrushikesh-git** [comment]
i have made changes now please try to merge @pankajkumarbij

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
> > @hrushikesh-git Nice Work
> > But there are no file changes is shown in PR, I think all files that you have changed are not pushed.
> 
> Please guide me what should i do as i am new to git hub

@hrushikesh-git Sorry I have not seen your comment because I was busy in some Work.
No problem You will learn with practice.
Keep it up

Nice Work.
Thanks for contributing to this project.

**Comment by hrushikesh-git** [comment]
> > > @hrushikesh-git Nice Work
> > > But there are no file changes is shown in PR, I think all files that you have changed are not pushed.
> > 
> > 
> > Please guide me what should i do as i am new to git hub
> 
> @hrushikesh-git Sorry I have not seen your comment because I was busy in some Work.
> No problem You will learn with practice.
> Keep it up
> 
> Nice Work.
> Thanks for contributing to this project.

Thanks for such amazing opportunity

**Pull request merged**
