### PR TITLE
Modified .GitIgnore file

### LINKED ISSUE #74: Add required files and folders in .gitignore for frontend and backend both.
Add required files and folders in .gitignore for frontend and backend both.

ex: node_modules, package-lock.json, .eslintcache etc.

you can search about it which files and folders should be in .gitignore.

### PR DESCRIPTION
**Pull request by srk224**
Added the required files and folder in .gitignore file

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@srk224 Nice Work
I think package-lock.json and server(node.js and mongodb part) folder files and folders are also should be in the .gitignore file.

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@srk224 Nice Work
I think package-lock.json and server(node.js and mongodb part) folder files and folders are also should be in the .gitignore file.

**Comment by srk224** [comment]
Should i also add the package-lock.json and 
and create one more .gitignore file in the server folder and add the (node.js and mongodb part) folder files???

**Comment by pankajkumarbij** [comment]
> files

I am not sure about the package-lock.json file you search about it that it should be in the .gitignore file or not.

No need to make another .gitignore file for the server separately, you should add server/file-name or server/folder-name in the existing .gitignore file.

**Comment by srk224** [comment]
I searched 
package.lock.json should not be added in .gitignore file and neither the mongodb folder files
i have added the node.js files of the server folder in .gitignore
What should I do next?

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@srk224 nice work.
Thanks for contributing to this project.

**Pull request merged**
