### PR TITLE
Enable the contact us form submissions through formspree 

### LINKED ISSUE #75: Handling Contact Us Form submission using Formspree API
## Is your feature request related to a problem? Please describe.
Creating Contact Us Form using Formspree.

## Describe the solution you'd like
I'll create contact-us form UI using React JS on the frontend and send the data of the user to the project admin email through Formspree API.

I'm going to edit the contact-us.js file and update it using react functional component i.e, Hooks. After that, on submission of the contact-us form, I'll send the user data to the project's admin email, using Formspree API.

## Additional context
By using Formspree we don't require to connect our frontend contact-us form to the backend to store the data in the database.

### PR DESCRIPTION
**Pull request by healer9**
## `FORMSPREE_API_KEY=ENTER YOUR FROMSPREE API KEY HERE`

formspree-api-key

### CODE REVIEW

**Comment by healer9** [comment]
## @pankajkumarbij  I also remove all the unnecessary files related to the contact-us form handling at the backend. 😎

**Comment by healer9** [comment]
@pankajkumarbij  I also update the styling of textarea tag in the contact-us form

textarea-styling
.

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@healer9 Nice Work
Thanks for contributing to this project.
I will check and tell you if I found any problem related to the contact us page.

**Comment by healer9** [comment]
> @healer9 Nice Work
> Thanks for contributing to this project.
> I will check and tell you if I found any problem related to the contact us page.

@pankajkumarbij  Yeah sure. ☺

Let me know if there is any issue reagarding this pull request.

**Comment by pankajkumarbij** [comment]
@healer9 It's Working.

Thanks for putting a nice feature in this project.

**Pull request merged**
