### PR TITLE
Redesigned the navigation bar

### LINKED ISSUE #562: Improving navigation bar
## Is your feature request related to a problem? Please describe.
 I would like to improve the navigation bar.

### PR DESCRIPTION
**Pull request by akshatvirmani**
## Related issue?
close: #562 

## Describe the changes you've made
changes in navigation bar
## Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

# Screenshots 
image

### CODE REVIEW

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@akshatvirmani send a full-page screenshot because I think this blue type of color is not match with other website design.

**Comment by akshatvirmani** [comment]
Sir, I was thinking of changing the other components design too. As this blue colored theme will match the easy-job-intern logo in the website.

**Comment by pankajkumarbij** [comment]
@akshatvirmani I want to design the whole website in a dark theme color combination so please try to make dark all things if they not.
Dark means not only black color but theme should be dark.

**Comment by akshatvirmani** [comment]
Okay Sir. I will work on dark theme then.

**Comment by pankajkumarbij** [comment]
> Okay Sir. I will work on dark theme then.

ok

**Comment by akshatvirmani** [comment]
image


Sir, Is this design okay?

**Comment by pankajkumarbij** [comment]
@akshatvirmani It's fine for now.

**Pull request merged**
