### PR TITLE
Update employer profile

### LINKED ISSUE #200: Backend for Update profile option for an employer
## Backend logic for Update profile for employer
Currently, the project does not have any profile update option for an employer
I will create a patch request for the same (working on the backend part)
@pankajkumarbij can you please assign this issue to me?

### PR DESCRIPTION
**Pull request by mitalirs**
Fixes #200 
An employer will now be able to update his/her profile with the added route
I have tested the route and it works fine

### CODE REVIEW

**Review by pankajkumarbij — APPROVED** [review]

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@mitalirs After merging your PR related to token there are not able to log in as a student please check and update the code with this PR.

**Comment by mitalirs** [comment]
@pankajkumarbij, which PR is causing the problem, could you please specifically mention the id?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij, which PR is causing the problem, could you please specifically mention the id?

https://github.com/pankajkumarbij/easy-job-intern/pull/195

**Comment by mitalirs** [comment]
@pankajkumarbij, I have created a new PR #214 that fixes the student login problem, please check that

**Review by pankajkumarbij — APPROVED** [review]

**Pull request merged**
