### PR TITLE
updated contributing.md

### LINKED ISSUE #159: Clearer instruction for local setup and running
make changes in the readme  so that contributors can work and run the frontend and backend separately

## Screenshots for reference
Screenshot (43)

### PR DESCRIPTION
**Pull request by Subham142**
#159 

added clearer instruction for frontend and backend seperatly

### CODE REVIEW

**Comment by Subham142** [comment]
@pankajkumarbij  please review the pr 
i don't know why it didn't connect to #159 
please label it here

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@Subham142 Why you put the guidelines about the front end and backend before the fork step.

Please manage Full contributing.MD file step by step starts to end so a contributor can read it step by step and can set up the project easily.

Start first step to find issue-->fork-->clone-->setup project locally(frontend and backend)--> and so on ..

All other steps are already there you have to put only your frontend and backend part guidelines after the clone section.

**Comment by Subham142** [comment]
@pankajkumarbij  please review the changes

**Review by pankajkumarbij — COMMENTED** [review]
@Subham142 Nice Work now it's fine but I think we can run the server(Backend) ```node index``` command or ```nodemon``` not by ```npm run server```.

Check and change it for the backend.

**Comment by Subham142** [comment]
@pankajkumarbij  please check
Really sorry for late changes ,my exams are going on

**Review by pankajkumarbij — CHANGES_REQUESTED** [review]
@Subham142 We can not run properly Backend using the ```npm start``` command. change run command for backend ```node index``` instead of ```npm start```.

**Comment by pankajkumarbij** [comment]
@Subham142 You have to require only one change please do it properly Then I will merge your PR.

You have to change the command for backend ```node index``` instead of ```npm start```.

**Comment by Subham142** [comment]
@pankajkumarbij  done

**Review by pankajkumarbij — APPROVED** [review]

**Comment by pankajkumarbij** [comment]
@Subham142 Nice Work
Thanks for contributing to this project.

**Pull request merged**
