### PR TITLE
Fix #26: added terms and condition page

### LINKED ISSUE #26: Design a general terms and condition page
Design general terms and condition page using react-bootstrap.

### PR DESCRIPTION
**Pull request by soumya-badkul**
image

### CODE REVIEW

**Comment by pankajkumarbij** [comment]
@soumya-badkul Make it a little bit pointwise and stylish (just add some style and bullet points and remove extra paragraphs)

**Comment by soumya-badkul** [comment]
image

**Comment by soumya-badkul** [comment]
image

**Comment by pankajkumarbij** [comment]
@soumya-badkul Thanks for contributing to this project.

**Pull request merged**
